// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCb9YqIhAdZDi-1alW4kACWuuj8GhdFRo',
    appId: '1:499720133771:web:d1a2b3c1c174b88305088e',
    messagingSenderId: '499720133771',
    projectId: 'plandate-1ead3',
    authDomain: 'plandate-1ead3.firebaseapp.com',
    storageBucket: 'plandate-1ead3.firebasestorage.app',
    measurementId: 'G-M430L2J6E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhCzZjZlfPBu-JhtrmeSmQ_aYQhYBUK9k',
    appId: '1:499720133771:android:157c23db3b92531405088e',
    messagingSenderId: '499720133771',
    projectId: 'plandate-1ead3',
    storageBucket: 'plandate-1ead3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqnCCRNX1GpN2DCkSk_wnwMvPsUYJenI',
    appId: '1:499720133771:ios:bc07b342d5f7bd4f05088e',
    messagingSenderId: '499720133771',
    projectId: 'plandate-1ead3',
    storageBucket: 'plandate-1ead3.firebasestorage.app',
    iosBundleId: 'com.example.datingplaningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqnCCRNX1GpN2DCkSk_wnwMvPsUYJenI',
    appId: '1:499720133771:ios:bc07b342d5f7bd4f05088e',
    messagingSenderId: '499720133771',
    projectId: 'plandate-1ead3',
    storageBucket: 'plandate-1ead3.firebasestorage.app',
    iosBundleId: 'com.example.datingplaningapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCb9YqIhAdZDi-1alW4kACWuuj8GhdFRo',
    appId: '1:499720133771:web:71976a145d5703a205088e',
    messagingSenderId: '499720133771',
    projectId: 'plandate-1ead3',
    authDomain: 'plandate-1ead3.firebaseapp.com',
    storageBucket: 'plandate-1ead3.firebasestorage.app',
    measurementId: 'G-K0NSRL077W',
  );
}
